version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rm94669
      POSTGRES_PASSWORD: 140204
      POSTGRES_DB: oracle
    ports:
      - 1521:1521
